language: python
sudo: false
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
  - env: TOXENV=coverage
install:
- pip install -U pip tox codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: cfhamlet
  password:
    secure: ne7Brf0Nc/PCTEWGgOwV3khEJjUIJu4qP5DDi6ylS8YBmlUbkxvJUSIwRL8E067txapVC0PE73OEBSNZ/XjK+zg6wTnudE/RoqcMrLQ7FcUAUqilJBT+B1NINc8Nr/rTr3REICzQqgeG393PLExiSaOFy4KB4v9tB8J3tqxMc1UeeP6TekGnSEPKkNL+s93GjgQnvlmU39KZfW543zKnkhzOjT8wT/0sK8FahbRvOLlNNekdQ996+46nHJ1S3kgl/nWA6xtdiQDPgHIm46ICZgDuITDVMi8HkM4WMbBwfhDJBRpIx7Bv229a0p+IQR4EepSDeBrW50bvHtR52ctJPc17YJRZFQ8yZrdRsG5ZG+MYZGppRlEOckvbGmmPg+4YLEz/DcW2ncY7Z2X4dilX5uJUY7sK9jusramvPJB6kgnbhwaL/pm5HNVUWZnPxA0fK8a2eJS8tycnIKpNftAzkIkBqjK1ztcKabMUeWnTO7YE3a9Gt05kNDOss1dnzXpviW9QpbngAdAoMgJwa7Az+K8o5xzImj+BnWIPBXhlBhalSVg0r8sMP/CsYILyo6TqtQsYk/XZJRMYAHftIF+sq4h1lynJTezPxrczYvkstlH045WQB+HinVgFWhdZIqm9Pk6Jxf6Jft+UFVruCuVmVuZfyoPwe98ZWnmqiEU4riw=
  true:
    tags: true
    condition: ${TOXENV} == py27
